swagger: "2.0"
info:
  description: "Initial version of share API. Development in progress. Use 'einstein' username."
  version: "-1.0.0"
  title: "Share API"
# host: ""
basePath: "/api/cs3"

tags:
- name: "shares"
  description: "Share operations"

paths:
  /shares:
    post:
      tags:
      - "shares"
      summary: "Creates a share"
      description: ""
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "endpoint"
        description: "endpoint path, default /"
        required: true
      - in: "body"
        name: "file_path"
        description: "Path with file name, e.g. /test.yml"
        required: true
      - in: "body"
        name: "grantee"
        description: "Share receiver's opaque_id"
        required: true
      - in: "body"
        name: "idp"
        description: "ID provider address"
        required: true
      - in: "body"
        name: "role"
        description: "role of a share receiver"
        required: true
        items:
          type: "string"
          enum:
          - "viewer"
          - "editor"
      - in: "body"
        name: "grantee_type"
        description: ""
        required: true
        items:
          type: "string"
          enum:
          - "user"
          - "group"
      responses:
        "201":
          description: "Share created"
        "405":
          description: "Invalid input"
        "500":
          description: "Error creating share"

    put:
      tags:
      - "shares"
      summary: "Updates a share"
      description: ""
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "share_id"
        description: "ID of a share"
        required: true
      - in: "body"
        name: "role"
        description: ""
        required: true
        items:
          type: "string"
          enum:
          - "editor"
          - "viewer"
      responses:
        "204":
          description: "Share updated"
        "405":
          description: "Invalid input"
        "500":
          description: "Error updating share"

    delete:
      tags:
      - "shares"
      summary: "Deletes a share"
      description: ""
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "share_id"
        description: "ID of a share"
        required: true
      responses:
        "204":
          description: "Share deleted"
        "405":
          description: "Invalid input"
        "500":
          description: "Error deleting share"

  /shares/list:
    get:
      tags:
      - "shares"
      summary: "Get all given shares"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "Shares returned"
        "405":
          description: "Invalid input"
        "500":
          description: "Error returning shares"

  /shares/file:
    get:
      tags:
        - "shares"
      summary: "Return grantees for file"
      description: ""
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "file_path"
          description: "Path with file name, e.g. '/home/test.txt'"
          required: true
      responses:
        "200":
          description: "Grantees returned"
        "405":
          description: "Invalid input"
        "500":
          description: "Error returning grantees"

  /shares/received:
    get:
      tags:
      - "shares"
      summary: "Get all received shares"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "Shares returned"
        "405":
          description: "Invalid input"
        "500":
          description: "Error returning shares"