name: Build Docker image

on:
  pull_request:
    branches: 
      - '*'

jobs:
  build-extension:
    uses: ./.github/workflows/workflow-build-python-package.yml
    with:
      create_dist: true
  build-docker:
    needs: build-extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: cs3api4lab-dist
          path: dist
      - name: Build the Docker image
        run: docker build  .
