name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Release bump: major, minor or patch"
        required: true
        default: "patch"

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            bump2version
      - name: Bump and tag
        run: |
          git config --local user.email "bot@sciencemesh.io"
          git config --local user.name "sciencemesh[bot]"
          bump2version ${{ github.event.inputs.bump }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
          tags: true