name: Build Python package

on: 
  workflow_call:
    inputs:
      create_dist:
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: '**/setup.py'
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
      - name: Installation dependencies
        run: pip install -U jupyterlab==3.0 check-manifest
      - name: Yarn dependencies
        run:  jlpm
      - name: Build the extension
        run: |
          set -eux
          jlpm run eslint:check
          pip install .
      - name: Check extensions is enabled
        run: |
          jupyter server extension list 2>&1 | grep -ie "cs3api4lab.*OK"
          jupyter labextension list 2>&1 | grep -ie "cs3api4lab.*OK"
          # python -m jupyterlab.browser_check # Disable test for lack of infrastructure
      - name: Create Dist
        if: ${{ inputs.create_dist }}
        run: |
          pip install build
          python -m build --sdist
      - uses: actions/upload-artifact@v3
        if: ${{ inputs.create_dist }}
        with:
          name: cs3api4lab-dist
          path: dist


